[project]
name = "robotic-arm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "keyboard>=0.13.5",
    "mediapipe>=0.10.33",
    "mqtt>=0.0.1",
    "opencv-python>=4.13.0.92",
    "paho-mqtt>=2.1.0",
    "pyserial>=3.5",
]
